cache:
 paths:
 - /root/.m2/repository
 
stages:
 - build
 - deploy
 - openMr

build:
 stage: build
 image: maven:3.3.9-jdk-8
 script:
 - mvn clean package
 tags:
 - docker
 
deploy_staging:
 stage: deploy
 image: ruby:2.3
 script:
 - apt-get update -qy
 - apt-get install -y ruby-dev
 - gem install dpl
 - dpl --provider=heroku --app=ms-trick-backend-staging --api-key=${HEROKU_API_KEY}
 environment:
    name: staging
    url: https://ms-trick-backend-staging.herokuapp.com/
  only:
 - ms-trick-backend
 tags:
 - docker
 
Open Merge Request:
  image: tmaier/gitlab-auto-merge-request:1
  before_script: [] # We do not need any setup work, let's remove the global one (if any)
  variables:
    GIT_STRATEGY: none # We do not need a clone of the GIT repository to create a Merge Request
  stage: openMr
  only:
    - /^feature\/*/ # We have a very strict naming convention
  script:
    - merge-request.sh # The name of the script